import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  title: "Geetanjali | Full Stack Developer",
  description:
    "Geetanjali is a MERN Stack Developer passionate about backend systems, security, and scalable web applications.",
  keywords: [
    "Geetanjali",
    "MERN Developer",
    "Full Stack Developer",
    "Backend Developer",
    "Next.js Portfolio",
  ],
  openGraph: {
    title: "Geetanjali | Full Stack Developer",
    description:
      "Portfolio of Geetanjali - MERN Stack Developer and Backend Engineer.",
    url: "https://geetanjali-portfolio.vercel.app",
    siteName: "Geetanjali Portfolio",
    // images: [
    //   {
    //     url: "/og-image.png",
    //     width: 1200,
    //     height: 630,
    //   },
    // ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Geetanjali | Full Stack Developer",
    description:
      "Portfolio of Geetanjali - MERN Stack Developer and Backend Engineer.",
    // images: ["/og-image.png"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
